### ISSUE TITLE
Validate incoming data

### ISSUE THREAD

**Issue by wzalazar** [poetapp/node#172]
With the goal to protect the API, we have to implement a validation system. I suggest creating a middleware with Joi.

**Comment by lautarodragan** [comment]
We already have something like this in place:

https://github.com/poetapp/node/blob/29d3fe283e0286345fd407baa8624d2f8a3ae27b/src/API/Router.ts#L79-L94

Maybe we could refactor that to use `isValidClaim`.

Funny fact: I left a TODO comment in poet-js mentioning we could use Joi, too.

https://github.com/poetapp/poet-js/blob/e08a88a96f82dbb342e9b8521ed07d5d949e3698/src/Interfaces.ts#L12-L22

But is this actually _required_ right now, or just a nice to have? Do our current checks suffice?

Tagging @jwicks31 @kennylavender who also worked on this.

**Comment by wzalazar** [comment]
I think is a nice to have, the more important endpoint is secure with the above implementation. But 

https://github.com/poetapp/node/blob/01888af282a7a0583b36b0f711c2aff43d3dd8cb/src/API/Router.ts#L59-L63

https://github.com/poetapp/node/blob/01888af282a7a0583b36b0f711c2aff43d3dd8cb/src/API/Router.ts#L70-L74

these endpoints we don't check the types

**Comment by lautarodragan** [comment]
Thanks @wzalazar!

For reference: did a call with Walter yesterday. This is the gist: the body of the single call that supports body, `POST /works`, is already checked (with isClaim, etc), so it's safe; but query params aren't validated.

### The Risk

Query params, if used as-are in database queries, could be dangerous. But given the simple nature of the queries we're currently doing in the node (just simple equality checks for these two endpoints), there's no risk at the moment.

### Solution

In the future we should make sure the parameters being passed to the MongoDB driver are of the type we expect (strings in these two cases, never objects); or assume they are because we trust that validation was done in an upper layer (for example, the router). 

I'd personally enforce both validation, so the different units don't need to rely on each other so much and have predictable behavior as independent units.
