### ISSUE TITLE
Poet/node health check

### ISSUE THREAD

**Issue by WesleyCharlesBlake** [poetapp/node#194]
We need to define a container healthcheck for the poet node service, as querying the service container port throws a 404 (as it is not authenticated with a frost api token, so the request fails).

Two ways we could approach this:
1. create a simple health check for node (eg `/healthz`) that responds with a 200 OK
1. have a dev api token that is part of the health check request - this will need some research though. Im not sure if this would create some risk though.

Im in favour of the simple solution of creating an unauthenticated health check endpoint that we can use.

**Comment by warrenv** [comment]
I agree with an unauthenticated health check.

**Comment by lautarodragan** [comment]
We'll add a `/health`. Or `healthz`? Was the `z` in `healthz` a typo or intentional?

Just for clarity, the node doesn't require authentication for any endpoint. It just consumes already-signed data or returns it. In particular, any `GET` endpoint works out of the box. Frost API Tokens are for the Frost API :grinning: 

404 is a resource not found. It's returned when you hit and endpoint that doesn't exist or try to retrieve a work that doesn't exist, in general.

**Comment by WesleyCharlesBlake** [comment]
Actually figured out what you just confirmed  haha. Query the `/works` endpoint will respond with a 200 OK so no need for a dedicated health check endpoint right now!
