### ISSUE TITLE
Questions about poet architecture

### ISSUE THREAD

**Issue by junbeomlee** [poetapp/node#55]
Hi

I was impressed with your architecture. I am developing a private blockchain called it-chain. As the development progresses, the Peer becomes more complicated, and I am thinking about switching Peer to MSA form. 

I have some questions about your architectural decisions

1. You have used Rabbitmq based on asynchronous communication as an internal communication, but some requests may need to work synchronously. If so,  I wonder if you plan to use Rabbitmq's rpc or partially use http. 

2. Now that you have a simple request so just using Rabbitmq is fine, but afterwards a lot of sophisticated requests can be implemented, and I wonder if we plan to use all of our communication with only Rabbitmq.

Thank you

from jun

**Comment by lautarodragan** [comment]
Thanks @junbeomlee ! 

We use RMQ for internal communication between modules, but the public API directly reads from the DB. Basically reads are sync, writes are async. This works well because the writes can be super expensive (going to IPFS, Blockchain, validating signatures, etc) while reads boil down to a `db.find(...)` which is really fast (assuming the Node is synced). 

There's no sync communication at all between internal modules. I like the concept of modules being completely blind about each other, simply listening to events they care for and shooting events not caring who may listen to them. But doing sync communication across modules (or micro services) or sending "commands" is pretty standard, too.

You're welcome to join our [Gitter](https://gitter.im/poetapp/Lobby) if you have any more questions or would like to discuss this
