### ISSUE TITLE
Stop using `ts-node` for tests

### ISSUE THREAD

**Issue by kennylavender** [poetapp/node#729]
`ts-node` is causing weird failures in our test scripts, see #726

Update the scripts in package.js to use the `dist` folder instead of `ts-node`

For example:

```"test:integration": "ts-node -r tsconfig-paths/register -r reflect-metadata --files ./tests/integration/index.ts",```
to
```"test:integration": "node  ./dist/babel/tests/integration/index.js",```

The test in `tests/API/PostFile.ts` use a markdown file fixture for streams, the markdown doesn't get copied over to the dist folder so this test will need to be adjusted.

**Comment by warrenv** [comment]
I see two problems with this approach:
  1. It slows down the test run.
  2. It requires a build to be run before running the integration tests.

The current configuration was chosen specifically to cover these two areas.

I would like to see if we can correct the problem via typescript configuration changes before adopting the solution proposed here.

**Comment by kennylavender** [comment]
@warrenv 

> It slows down the test run.
Seems like this would be minor, the additional time is likely just to be the file system.

> It requires a build to be run before running the integration tests.
Seems to have a simple solution unless I am missing something, just add a build before test run inside the script for both integration and functional?
```"test:integration": "npm run build && node ./dist/babel/tests/integration/index.js",```

@wzalazar just pinged me on slack, he is looking at the issue now, so Il wait and see how that goes.

**Comment by lautarodragan** [comment]
Agreed on everything Warren said. I'm coordinating with Walter via slack because we can't spend too much time on this now, and Kenny already has a working solution.

**Comment by lautarodragan** [comment]
@kennylavender 

> Seems like this would be minor, the additional time is likely just to be the write to the file system 

Agreed. It can be a bit bothersome when doing TDD, but it is minor.

> ( twice, unfortunately, although babel can now be used to compile typescript, so one of the steps could be removed )

[Using the TypeScript compiler is still the preferred way to build TypeScript](https://blogs.msdn.microsoft.com/typescript/2018/08/27/typescript-and-babel-7/), but we could go the other way round and get rid of Babel with [tsconfig-paths](https://www.npmjs.com/package/tsconfig-paths) if we really really wanted to. We can discuss alternatives after mainnet, but like you said, it's a minor issue.

> Seems to have a simple solution unless I am missing something, just add a build before test run inside the script for both integration and functional?

Let's leave the responsibility of building to whoever is calling `test:integration`. It's not immediately obvious that running the integration tests will destroy your dist, and from time to time it's easier to debug things by playing around with the output js manually rather than modifying and building the ts.

In our case it only means we need to `docker-compose up -d --build` before `docker-compose exec npm run test:integration` if running the tests manually in our local machines. Travis already builds everything before running tests so no changes there.

Picking up @wzalazar's [comment](https://github.com/poetapp/node/pull/721#issuecomment-436450107):

>  I tried to reproduce the error in my local in different ways and I couldn't. I don't' receive any error in the logs

Let's go ahead with dropping ts-node for now. If we find running tests without it is really painful or bug-prone we can come back to this.
