### ISSUE TITLE
No file found incorrectly being logged as error

### ISSUE THREAD

**Issue by lautarodragan** [poetapp/node#806]
https://github.com/poetapp/node/blob/96eb4658332e9d221818e4f633d39b74389d53ce/src/API/Middlewares/HttpExceptionsMiddleware.ts#L9-L25

@kennylavender sorry I missed this in https://github.com/poetapp/node/pull/784, but the `else` branch here is for errors that we aren't expecting (like the mongoDB driver throwing due to a broken connection).

We need to change the middleware's code back to how it was, and use `IllegalArgumentException` for the "No Files" exception.

**Comment by kennylavender** [comment]
@lautarodragan I think it would be better to just move the log statement into the nested else for now, and later on and remove the other if statements that check individual custom errors at a later time.

IMO this pattern of checking individual custom errors seems to be out of place in this file. I think if an error gets thrown in a route handler, that route handler should be responsible for exposing or keeping the error hidden.

The handler could either
- catch the error and use catch.throw to expose the error to the user
- catch the error and ignore it
- catch the error and rethrow it in a non exposed fashion so that a 503 happens.
- don't catch the error and let a 503 happen.

My suggestion for now:

```ts
import * as Koa from 'koa'

import { IllegalArgumentException, NotFoundException } from '@po.et/poet-js'

export const HttpExceptionsMiddleware: Koa.Middleware = async (context: any, next: () => Promise<any>) => {
  try {
    await next()
  } catch (exception) {
    if (exception instanceof IllegalArgumentException) {
      context.body = exception.message
      context.status = 422
    } else if (exception instanceof NotFoundException) {
      context.body = exception.message
      context.status = 404
    } else {
      if (exception.expose) {
        context.body = exception.message || 'Internal Server Error'
        context.status = exception.status || 503
      } else {
        if (context.logger)
          context.logger.error({ exception }, 'Error Caught at Middleware')

        context.body = 'Internal Server Error'
        context.status = 503
      }

      context.app.emit('error', exception, context)
    }
  }
}
```

and eventually, we update the route handlers to handle these other if statements so this file just simply becomes:

```ts
import * as Koa from 'koa'

export const HttpExceptionsMiddleware: Koa.Middleware = async (context: any, next: () => Promise<any>) => {
  try {
    await next()
  } catch (exception) {
    if (exception.expose) {
      context.body = exception.message || 'Internal Server Error'
      context.status = exception.status || 503
    } else {
      if (context.logger)
        context.logger.error({ exception }, 'Error Caught at Middleware')

      context.body = 'Internal Server Error'
      context.status = 503
    }

    context.app.emit('error', exception, context)
  }
}
```
