### ISSUE TITLE
API is directly accessing health collection

### ISSUE THREAD

**Issue by kennylavender** [poetapp/node#874]
Our API module is directly accessing the health collection.

https://github.com/poetapp/node/blob/master/src/API/HealthController.ts#L33

This goes against our Service guidelines.
https://github.com/poetapp/node/blob/master/src/README.md#service-guidelines

The API does need to get to this information though. If these were true micro-services it would probably be done through a rest API or some other synchronous method.

It looks like rabbitMQ might support [synchronous RPC's (Remote Procedure Calls)](https://www.rabbitmq.com/tutorials/tutorial-six-python.html). This could be looked into further.

**Comment by lautarodragan** [comment]
This is more an issue with how we're wording our README than the implementation.

See https://microservices.io/patterns/data/cqrs.html

In practice what we'd want is for API to access read-only replicas of the databases rather than the same database directly. That requires no change to the code, though.
